import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Shop {
    shopName: string;
    address: string | null;
    phone: string;
    email?: string;
}

interface JobSheet {
    jobId: string;
    customerName: string;
    customerPhone: string;
    customerAddress?: string | null;
    deviceModel?: string | null;
    deviceType?: string | null;
    problemDesc?: string | null;
    accessories?: string | null;
    receivedAt: Date;
    expectedAt?: Date | null;
    estimatedCost?: number | null;
    advanceAmount?: number | null;
    status: string;
}

export const generateJobBill = (shop: Shop, job: JobSheet) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    
    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text(shop.shopName, pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    // Address (Split if long)
    const addressLines = doc.splitTextToSize(shop.address || 'Address not set', 150);
    doc.text(addressLines, pageWidth / 2, 28, { align: 'center' });
    doc.text(`Phone: ${shop.phone}`, pageWidth / 2, 30 + (addressLines.length * 4), { align: 'center' });

    // Line Divider
    const headerBottom = 40 + (addressLines.length * 4);
    doc.setDrawColor(200, 200, 200);
    doc.line(10, headerBottom, pageWidth - 10, headerBottom);

    // --- Title ---
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text("REPAIR INVOICE / JOB SHEET", pageWidth / 2, headerBottom + 12, { align: 'center' });

    // --- Job & Customer Details (2 Columns) ---
    const startY = headerBottom + 25;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    // Left: Customer Info
    doc.text("CUSTOMER DETAILS:", 15, startY);
    doc.setFont('helvetica', 'bold');
    doc.text(job.customerName, 15, startY + 6);
    doc.setFont('helvetica', 'normal');
    doc.text(`Phone: ${job.customerPhone}`, 15, startY + 11);
    if(job.customerAddress) {
        doc.text(`Addr: ${job.customerAddress}`, 15, startY + 16);
    }

    // Right: Job Info
    doc.text("JOB DETAILS:", 120, startY);
    doc.setFont('helvetica', 'bold');
    doc.text(`Job ID: ${job.jobId}`, 120, startY + 6);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date(job.receivedAt).toLocaleDateString()}`, 120, startY + 11);
    doc.text(`Status: ${job.status}`, 120, startY + 16);
    
    // --- Device Table ---
    // @ts-ignore
    autoTable(doc, {
        startY: startY + 25,
        head: [['Device', 'Model', 'Issue / Problem', 'Accessories']],
        body: [
            [
                job.deviceType || '-', 
                job.deviceModel || '-', 
                job.problemDesc || '-', 
                job.accessories || '-'
            ]
        ],
        theme: 'grid',
        headStyles: { fillColor: [66, 66, 66], textColor: 255 },
        styles: { fontSize: 10, cellPadding: 3 }
    });

    // --- Cost Calculation ---
    // @ts-ignore
    const finalY = doc.lastAutoTable.finalY + 10;
    
    // Cost Table (Right Aligned mostly)
    // @ts-ignore
    autoTable(doc, {
        startY: finalY,
        body: [
            ['Estimated Cost:', `Rs. ${job.estimatedCost || 0}`],
            ['Advance Paid:', `Rs. ${job.advanceAmount || 0}`],
            [{ content: 'TOTAL PAYABLE:', styles: { fontStyle: 'bold' } }, { content: `Rs. ${(job.estimatedCost || 0) - (job.advanceAmount || 0)}`, styles: { fontStyle: 'bold' } }]
        ],
        theme: 'plain',
        columnStyles: {
            0: { halign: 'right', cellWidth: 140, fontStyle: 'bold' },
            1: { halign: 'right', cellWidth: 40 }
        }
    });

    // --- Footer ---
    const footerY = 250;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    
    doc.text("Generated by FixSure - Repair Management System", 10, 285);
    doc.save(`${job.jobId}_Invoice.pdf`);
};
